export const REGISTER_RESTAURANT_REQUEST = "REGISTER_RESTAURANT_REQUEST";
export const REGISTER_RESTAURANT_SUCCESS = "REGISTER_RESTAURANT_SUCCESS";
export const REGISTER_RESTAURANT_FAIL = "REGISTER_RESTAURANT_FAIL";

export const LOAD_RESTAURANT_REQUEST = "LOAD_RESTAURANT_REQUEST";
export const LOAD_RESTAURANT_SUCCESS = "LOAD_RESTAURANT_SUCCESS";
export const LOAD_RESTAURANT_FAIL = "LOAD_RESTAURANT_FAIL";
export const CLEAR_ERRORS = "CLEAR_ERRORS";

export const ALL_RESTAURANT_REQUEST = "ALL_RESTAURANT_REQUEST";
export const ALL_RESTAURANT_SUCCESS = "ALL_RESTAURANT_SUCCESS";
export const ALL_RESTAURANT_FAIL = "ALL_RESTAURANT_FAIL";

export const DELETE_RESTAURANT_REQUEST = "DELETE_RESTAURANT_REQUEST";
export const DELETE_RESTAURANT_SUCCESS = "DELETE_RESTAURANT_SUCCESS";
export const DELETE_RESTAURANT_RESET = "DELETE_RESTAURANT_RESET";
export const DELETE_RESTAURANT_FAIL = "DELETE_RESTAURANT_FAIL";

export const UPDATE_RESTAURANT_REQUEST = "UPDATE_RESTAURANT_REQUEST";
export const UPDATE_RESTAURANT_SUCCESS = "UPDATE_RESTAURANT_SUCCESS";
export const UPDATE_RESTAURANT_RESET = "UPDATE_RESTAURANT_RESET";
export const UPDATE_RESTAURANT_FAIL = "UPDATE_RESTAURANT_FAIL";

export const UPDATE_PROFILE_RES_REQUEST = "UPDATE_PROFILE_RES_REQUEST";
export const UPDATE_PROFILE_RES_SUCCESS = "UPDATE_PROFILE_RES_SUCCESS";
export const UPDATE_PROFILE_RES_RESET = "UPDATE_PROFILE_RES_RESET";
export const UPDATE_PROFILE_RES_FAIL = "UPDATE_PROFILE_RES_FAIL";
